apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nyk-api-servicemonitor
  namespace: monitoring
  labels:
    release: monitoring   # must match the helm release name of kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - dev
  selector:
    matchLabels:
      app: nyk-api        # must match labels on your Service
  endpoints:
    - port: http          # name of the Service port (not the number)
      interval: 30s
      path: /metrics
