apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nyk-demo-app.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "nyk-demo-app.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "nyk-demo-app.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "nyk-demo-app.name" . }}
    spec:
      containers:
        - name: web
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports: [ { containerPort: 80 } ]
