apiVersion: apps/v1
kind: Deployment
metadata:
  name: nyk-demo
  labels:
    app.kubernetes.io/name: nyk-demo
    app.kubernetes.io/part-of: nyk-demo
    app.kubernetes.io/component: web
    app.kubernetes.io/version: v0.1.0
spec:
  # Overridden by overlay (e.g., dev sets 1)
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: nyk-demo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nyk-demo
        app.kubernetes.io/part-of: nyk-demo
        app.kubernetes.io/component: web
    spec:
      containers:
        - name: app
          ##image: nginx:1.25-alpine
          image: ghcr.io/NYK-Logistics/nyk-web:latest
          ports:
            - name: http
              containerPort: 80
          readinessProbe:
            httpGet: { path: "/healthz.html", port: http }
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: "/healthz.html", port: http }
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            requests: { cpu: 50m, memory: 64Mi }
            limits:   { cpu: 250m, memory: 256Mi }

