apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml

# Optional labels applied to all manifests + selectors
labels:
  - pairs:
      app.kubernetes.io/part-of: nyk-demo
    includeSelectors: true
    includeTemplates: true

