apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nyk-demo
  labels:
    app.kubernetes.io/part-of: nyk-demo
  annotations:
    # If your controller uses class via annotation; otherwise prefer spec.ingressClassName
    # kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: traefik   # change to "traefik" if youâ€™re using Traefik instead
  rules:
    - host: nyk.localtest.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dev-nyk-demo
                port:
                  number: 80